outside_href:
  rails_tutorial: "https://www.railstutorial.org/"
  michael_harlt: "https://www.michaelhartl.com/"
  rails_tutorial_contact: "https://www.railstutorial.org/contact/"
  ruby_on_rails: "https://www.rubyonrails.org/"
  learn_enough: "https://learnenough.com/"
  rails_tutorial_book: "https://www.railstutorial.org/book"
  rails_tutorial_screencasts: "https://screencasts.railstutorial.org"
